Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -67,6 +67,15 @@ jobs:
     runs-on: ubuntu-latest
     needs: deploy
     steps:
+      - name: Wait for deployment
+        run: sleep 60  # Wait for 1 minute before verifying the page
+
       - name: Confirm GitHub Pages Deployment
         run: |
-          curl -s https://harshitsingh9003.github.io/Tirupati-INN-homestay-Varanasi | grep "Your page has been deployed."
+          http_status=$(curl -s -o /dev/null -w "%{http_code}" https://harshitsingh9003.github.io/Tirupati-INN-homestay-Varanasi)
+          if [ "$http_status" -eq 200 ]; then
+            echo "Deployment successful!"
+          else
+            echo "Deployment failed with status code: $http_status"
+            exit 1
+          fi
